"""End-to-end discrete dataset generation and model comparison workflow."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from friction_surrogate_xai.config.loader import project_root
from friction_surrogate_xai.data import DataLoader, LoadedDataset
from friction_surrogate_xai.discretization.comparison import (
    DiscreteComparisonArtifacts,
    OriginalVsDiscreteComparator,
)
from friction_surrogate_xai.discretization.config import (
    DiscretizationConfig,
    load_discretization_config,
)
from friction_surrogate_xai.discretization.generator import (
    DiscreteDatasetArtifacts,
    DiscreteDatasetGenerator,
)
from friction_surrogate_xai.discretization.mlflow_logging import DiscretizationMLflowLogger
from friction_surrogate_xai.eda.utils import ensure_directory


@dataclass(frozen=True)
class DiscretizationWorkflowArtifacts:
    """Artifacts generated by a full discretization workflow run."""

    datasets: dict[str, DiscreteDatasetArtifacts]
    comparisons: dict[str, DiscreteComparisonArtifacts]


class DiscretizationWorkflow:
    """Generate discrete datasets and compare original vs discrete inputs."""

    def __init__(
        self,
        config: DiscretizationConfig | None = None,
        data_loader: DataLoader | None = None,
    ) -> None:
        self.config = config or load_discretization_config()
        self.data_loader = data_loader or DataLoader()
        self.generator = DiscreteDatasetGenerator(config=self.config, data_loader=self.data_loader)
        self.comparator = OriginalVsDiscreteComparator(config=self.config)
        self.mlflow_logger = DiscretizationMLflowLogger(self.config.mlflow)

    def run(
        self,
        *,
        dataset_keys: tuple[str, ...] | None = None,
        target_columns: tuple[str, ...] | None = None,
        explicit_model_keys: tuple[str, ...] | None = None,
        compare: bool | None = None,
        log_to_mlflow: bool | None = None,
    ) -> DiscretizationWorkflowArtifacts:
        """Run dataset generation and optional original-vs-discrete comparisons."""
        loaded_datasets = self._load_selected(dataset_keys)
        generated: dict[str, DiscreteDatasetArtifacts] = {}
        comparisons: dict[str, DiscreteComparisonArtifacts] = {}

        for dataset_key, loaded_dataset in loaded_datasets.items():
            dataset_artifacts = self.generator.run_dataset(loaded_dataset)
            generated[dataset_key] = dataset_artifacts
            self._log_generation_if_needed(
                dataset_key=dataset_key,
                dataset_artifacts=dataset_artifacts,
                log_to_mlflow=log_to_mlflow,
            )

            should_compare = self.config.comparison.get("enabled", True) if compare is None else compare
            if should_compare:
                for target_name in self._target_columns(loaded_dataset, target_columns):
                    comparison = self.comparator.compare(
                        dataset_key=dataset_key,
                        original_dataframe=loaded_dataset.dataframe,
                        discrete_dataframe=dataset_artifacts.dataframe,
                        feature_columns=loaded_dataset.report.metadata.feature_columns,
                        target_name=target_name,
                        explicit_model_keys=explicit_model_keys,
                        log_to_mlflow=log_to_mlflow,
                    )
                    comparisons[f"{dataset_key}:{target_name}"] = comparison

        return DiscretizationWorkflowArtifacts(datasets=generated, comparisons=comparisons)

    def _load_selected(self, dataset_keys: tuple[str, ...] | None) -> dict[str, LoadedDataset]:
        if dataset_keys:
            return {
                dataset_key: self.data_loader.load(dataset_key)
                for dataset_key in dataset_keys
            }
        return self.data_loader.load_all()

    def _target_columns(
        self,
        loaded_dataset: LoadedDataset,
        target_columns: tuple[str, ...] | None,
    ) -> tuple[str, ...]:
        configured = target_columns or tuple(self.config.comparison.get("target_columns", ()))
        available = set(loaded_dataset.dataframe.columns)
        return tuple(target for target in configured if target in available)

    def _log_generation_if_needed(
        self,
        *,
        dataset_key: str,
        dataset_artifacts: DiscreteDatasetArtifacts,
        log_to_mlflow: bool | None,
    ) -> None:
        should_log = self.config.mlflow.get("enabled", True) if log_to_mlflow is None else log_to_mlflow
        if not should_log:
            return
        self.mlflow_logger.log_dataset_generation(
            dataset_key=dataset_key,
            artifact_dir=self._dataset_artifact_dir(dataset_artifacts),
            metadata=dataset_artifacts.metadata,
        )

    @staticmethod
    def _dataset_artifact_dir(dataset_artifacts: DiscreteDatasetArtifacts) -> Path:
        candidates = [
            path.parent
            for path in (dataset_artifacts.csv_path, dataset_artifacts.excel_path)
            if path is not None
        ]
        if candidates:
            return candidates[0]
        fallback = project_root() / "data" / "processed" / "discrete"
        return ensure_directory(fallback)
