"""Final project report generation."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from friction_surrogate_xai.eda.utils import ensure_directory
from friction_surrogate_xai.evaluation.reports import EvaluationReportWriter


@dataclass(frozen=True)
class FinalReportArtifacts:
    """Final report paths."""

    markdown_path: Path
    stage_table_path: Path


class FinalProjectReportWriter:
    """Write an integrated final project report from pipeline state."""

    def __init__(self, reports_config: dict[str, Any] | None = None) -> None:
        self.markdown = EvaluationReportWriter(reports_config or {})

    def write(
        self,
        *,
        run_id: str,
        state_rows: list[dict[str, Any]],
        root_dir: Path,
        config_summary: dict[str, Any],
    ) -> FinalReportArtifacts:
        """Write final Markdown and CSV stage table."""
        markdown_dir = ensure_directory(root_dir / "markdown")
        tables_dir = ensure_directory(root_dir / "tables")
        stage_table = pd.DataFrame(state_rows)
        stage_table_path = tables_dir / "pipeline_stage_status.csv"
        stage_table.to_csv(stage_table_path, index=False, encoding="utf-8")

        markdown_path = markdown_dir / "final_project_report.md"
        lines = [
            f"# Final Project Report: {run_id}",
            "",
            "## Scope",
            "",
            "This report is generated by the resumable final orchestration pipeline.",
            "",
            "## Configuration Summary",
            "",
            self.markdown._markdown_table(pd.DataFrame([config_summary])),
            "",
            "## Pipeline Stage Status",
            "",
            self.markdown._markdown_table(stage_table),
            "",
            "## Artifact Index",
            "",
        ]
        for row in state_rows:
            paths = row.get("artifact_paths", []) or []
            lines.append(f"### {row.get('name', '')}")
            if not paths:
                lines.append("- _No artifacts registered._")
            else:
                lines.extend(f"- `{path}`" for path in paths)
            lines.append("")

        failed = [row for row in state_rows if row.get("status") == "failed"]
        if failed:
            lines.extend(["## Failed Or Incomplete Stages", ""])
            for row in failed:
                lines.append(f"- `{row.get('name')}`: {row.get('message', '')}")
            lines.append("")

        markdown_path.write_text("\n".join(lines), encoding="utf-8")
        return FinalReportArtifacts(markdown_path=markdown_path, stage_table_path=stage_table_path)
