"""End-to-end uncertainty report orchestration."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from friction_surrogate_xai.config.loader import project_root
from friction_surrogate_xai.data import DataLoader
from friction_surrogate_xai.eda.utils import ensure_directory, sanitize_filename
from friction_surrogate_xai.models import ModelFactory
from friction_surrogate_xai.preprocessing import PreprocessingPipelineFactory
from friction_surrogate_xai.uncertainty.config import (
    UncertaintyConfig,
    load_uncertainty_config,
)
from friction_surrogate_xai.uncertainty.estimators import (
    BootstrapUncertaintyEstimator,
    GPRUncertaintyEstimator,
    UncertaintyResult,
)
from friction_surrogate_xai.uncertainty.mlflow_logging import UncertaintyMLflowLogger
from friction_surrogate_xai.uncertainty.plotting import UncertaintyPlotter
from friction_surrogate_xai.uncertainty.reports import (
    UncertaintyReportPaths,
    UncertaintyReportWriter,
    build_comparison_report,
)


@dataclass(frozen=True)
class UncertaintyArtifacts:
    """All artifacts generated by one uncertainty run."""

    dataset_key: str
    target_name: str
    root_dir: Path
    model_results: dict[str, UncertaintyResult]
    prediction_intervals: pd.DataFrame
    confidence_bands: pd.DataFrame
    summary: pd.DataFrame
    comparison: pd.DataFrame
    table_paths: tuple[Path, ...]
    figure_paths: tuple[Path, ...]
    markdown_paths: tuple[Path, ...]


class UncertaintyReportGenerator:
    """Generate uncertainty intervals and comparison reports for configured models."""

    def __init__(
        self,
        config: UncertaintyConfig | None = None,
        data_loader: DataLoader | None = None,
        model_factory: ModelFactory | None = None,
        preprocessing_factory: PreprocessingPipelineFactory | None = None,
    ) -> None:
        self.config = config or load_uncertainty_config()
        self.data_loader = data_loader or DataLoader()
        self.model_factory = model_factory or ModelFactory()
        self.preprocessing_factory = preprocessing_factory or PreprocessingPipelineFactory()
        self.report_writer = UncertaintyReportWriter(self.config.reports)
        self.plotter = UncertaintyPlotter(self.config.plots)
        self.mlflow_logger = UncertaintyMLflowLogger(self.config.mlflow)

    def generate(
        self,
        *,
        dataset_key: str,
        target_name: str,
        model_keys: tuple[str, ...] | None = None,
        X: pd.DataFrame | None = None,
        y: pd.Series | pd.DataFrame | None = None,
        dataframe: pd.DataFrame | None = None,
        params_by_model: dict[str, dict[str, Any]] | None = None,
        log_to_mlflow: bool | None = None,
    ) -> UncertaintyArtifacts:
        """Generate uncertainty reports for one dataset target."""
        X, y = self._resolve_data(
            dataset_key=dataset_key,
            target_name=target_name,
            X=X,
            y=y,
            dataframe=dataframe,
        )
        selected_models = model_keys or self.config.default_model_keys
        params_by_model = params_by_model or {}
        root_dir = self._run_root(dataset_key, target_name)
        tables_dir = ensure_directory(
            root_dir / self.config.output.get("tables_dir_name", "tables")
        )
        figures_dir = ensure_directory(
            root_dir / self.config.output.get("figures_dir_name", "figures")
        )
        markdown_dir = ensure_directory(
            root_dir / self.config.output.get("markdown_dir_name", "markdown")
        )

        model_results: dict[str, UncertaintyResult] = {}
        for model_key in selected_models:
            estimator = self._estimator_for(model_key)
            result = estimator.estimate(
                dataset_key=dataset_key,
                model_key=model_key,
                X=X,
                y=y,
                params_override=params_by_model.get(model_key),
            )
            model_results[model_key] = result

        prediction_intervals = pd.concat(
            [result.prediction_intervals for result in model_results.values()],
            ignore_index=True,
        )
        confidence_bands = pd.concat(
            [result.confidence_bands for result in model_results.values()],
            ignore_index=True,
        )
        summary = pd.concat(
            [result.summary for result in model_results.values()],
            ignore_index=True,
        )
        comparison = build_comparison_report(summary)
        figure_paths = self.plotter.write_all(
            confidence_bands=confidence_bands,
            comparison=comparison,
            figures_dir=figures_dir,
        )
        report_paths = self.report_writer.write(
            dataset_key=dataset_key,
            target_name=target_name,
            prediction_intervals=prediction_intervals,
            confidence_bands=confidence_bands,
            summary=summary,
            comparison=comparison,
            figure_paths=figure_paths,
            tables_dir=tables_dir,
            markdown_dir=markdown_dir,
        )

        should_log = self.mlflow_logger.enabled() if log_to_mlflow is None else log_to_mlflow
        if should_log:
            self.mlflow_logger.log_run(
                dataset_key=dataset_key,
                target_name=target_name,
                artifact_dir=root_dir,
                comparison=comparison,
                extra_metrics={
                    "model_count": len(model_results),
                    "prediction_interval_rows": len(prediction_intervals),
                },
            )

        return UncertaintyArtifacts(
            dataset_key=dataset_key,
            target_name=target_name,
            root_dir=root_dir,
            model_results=model_results,
            prediction_intervals=prediction_intervals,
            confidence_bands=confidence_bands,
            summary=summary,
            comparison=comparison,
            table_paths=report_paths.table_paths,
            figure_paths=figure_paths,
            markdown_paths=report_paths.markdown_paths,
        )

    def _estimator_for(
        self,
        model_key: str,
    ) -> GPRUncertaintyEstimator | BootstrapUncertaintyEstimator:
        if model_key == self.config.gpr_model_key:
            if not self.config.gpr.get("enabled", True):
                raise ValueError("GPR uncertainty is disabled in config.")
            return GPRUncertaintyEstimator(
                model_factory=self.model_factory,
                preprocessing_factory=self.preprocessing_factory,
                config=self.config.gpr,
                confidence_level=self.config.confidence_level,
            )
        if not self.config.bootstrap.get("enabled", True):
            raise ValueError("Bootstrap uncertainty is disabled in config.")
        return BootstrapUncertaintyEstimator(
            model_factory=self.model_factory,
            preprocessing_factory=self.preprocessing_factory,
            config=self.config.bootstrap,
            confidence_level=self.config.confidence_level,
            random_state=int(self.config.intervals.get("random_state", 42)),
        )

    def _resolve_data(
        self,
        *,
        dataset_key: str,
        target_name: str,
        X: pd.DataFrame | None,
        y: pd.Series | pd.DataFrame | None,
        dataframe: pd.DataFrame | None,
    ) -> tuple[pd.DataFrame, pd.Series | pd.DataFrame]:
        if X is not None and y is not None:
            return X.copy(), y.copy()

        if dataframe is None:
            loaded = self.data_loader.load(dataset_key)
            dataframe = loaded.dataframe
            feature_columns = loaded.report.metadata.feature_columns
        else:
            feature_columns = self.data_loader.catalog.schema.feature_columns

        if target_name not in dataframe.columns:
            raise KeyError(
                f"Target column '{target_name}' is not present in dataset '{dataset_key}'."
            )
        missing_features = [column for column in feature_columns if column not in dataframe.columns]
        if missing_features:
            raise KeyError(
                f"Dataset '{dataset_key}' is missing required feature columns: {missing_features}"
            )
        return (
            dataframe.loc[:, list(feature_columns)].copy(),
            dataframe.loc[:, target_name].copy(),
        )

    def _run_root(self, dataset_key: str, target_name: str) -> Path:
        configured_root = self.config.output_root
        root = (
            configured_root
            if configured_root.is_absolute()
            else project_root() / configured_root
        )
        return ensure_directory(
            root / sanitize_filename(dataset_key) / sanitize_filename(target_name)
        )
